spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
#              uri: http://localhost:8081
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/customers/**
            - id: r2
#              uri: http://localhost:8082
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/products/**
